- name: install shipping 
  hosts: shipping
  become: yes
  tasks: 
  - name: install maven
    ansible.builtin.dnf:
      name: maven 
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downlode shipping application
    ansible.builtin.get_url:
      url: roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: extract shipping application 
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes # to access the file from the target remote meachine

  - name: Install dependencies 
    ansible.builtin.command: mvn clean package
    args: 
      chdir: /app # to change the directory and run the command
  
  - name: rename jar file 
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: demon realode and start
    ansible.builtin.system_service:
      demon_relode: true

  - name: install mysql client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: check cities schema exists or not
    ansible.builtin.command: mysql -h mysql.mydevops.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print output
    ansible.builtin.debug:
      msg: "schema output: {{schema}}"
  
  - name: load cities data
    ansible.builtin.command: mysql -h mysql.mydevops.online -uroot -pRoboShop@1 < /app/schema/shipping.sql 
    when: schema.stdout != "1"
